### ISSUE TITLE
Automatically back up issues

### ISSUE THREAD

**Issue by fsteeg** [culturegraph/metafacture-documentation#1]
In our get together at SWIB15 (see [1]) we decided to use the issue tracker in this repo as our central place for all kinds of documentation. Since issues are not part of the Git repo, we decided to set up automatic backups for the issues using the GitHub API.

[1] http://etherpad.lobid.org/p/swib15-metafacture

**Comment by fsteeg** [comment]
Set up automatic backups, available at:
http://lobid.org/events/metafacture/backup

It's basically a copy of the response to this GitHub API call:
https://api.github.com/repos/culturegraph/metafacture-documentation/issues?state=all

A backup is created on any GitHub issues event, using a webhook posting to:
`http://lobid.org/events/metafacture`

That service is implemented in:
https://github.com/hbz/events (see https://github.com/hbz/events/issues/4 for some implementation details).

**Comment by guenterh** [comment]
@fsteeg 
Thanks Fabian for the setup of this backup. I haven't had the time to look into the details - it's interesting to use the Git API with events. I have heard of it but haven't used it so far.

Related to the documentation itself:
Hopefully I can start to put some first documentation as a starter into the repo of our project work done so far this week. Last week it wasn't possible.

I would like to add additional Github accounts of other "Metafactures" as team-members for this repo. But as far as I can see you have already write permissions for the whole Culturegraph namespace?

Best wishes to Cologne
Günter

**Comment by fsteeg** [comment]
@guenterh I have admin access to this repo for setting up and testing the webhook (for the backups). I don't have write permissions or admin access to the other Culturegraph repos. Perhaps @cboehme can give you admin access for this repo to add other members or add them for you.

**Comment by guenterh** [comment]
@fsteeg Christoph already granted admin access to me for the doc repository. I'm going to add additional users soon, Günter
@cboehme fyi

**Comment by fsteeg** [comment]
The current backup contains the issues only, without comments. We need to include data like:

https://api.github.com/repos/culturegraph/metafacture-documentation/issues/1/comments

**Comment by fsteeg** [comment]
The comments are now backed up in a `comments_data` field for each issue.

See: http://lobid.org/events/metafacture/backup
