### ISSUE TITLE
Metamorph: remove duplicates from array

### ISSUE THREAD

**Issue by philboeselager** [culturegraph/metafacture-documentation#6]
Is there already a way to remove duplicates from metamorph arrays?

Preferably, a "unique" attribute or option would exist within the "entity" tag.
Otherwise, the implementation of an ArrayDuplicateRemover would be the way to go, I guess. This solution should be more expensive in terms of calculation duration.

Corresponding issue: https://github.com/hbz/lobid-organisations/issues/18
Morph code used so far: https://github.com/hbz/lobid-organisations/blob/c72429235ddd3fe713449e39b8456df921f32b6b/src/main/resources/morph-enriched.xml#L304
Morph output: http://beta.lobid.org/organisations/DE-9
The occurrence of this duplicate is caused by input data. Nevertheless, it is desirable to have a removal option.

**Comment by dr0i** [comment]
With the `<occurrence only="1" />` directive (see https://github.com/hbz/lobid-organisations/commit/c40a5e70a972f6eae1bbf85dfebeaf30c5619126) it's possible to restrict the outcome exactly one entry.

**Comment by dr0i** [comment]
Closing.
